import { jest } from '@jest/globals';
import fs from 'fs-extra';
import path from 'path';
import os from 'os';

// We test the internal functions by importing analyzeFile indirectly
// Since functions are not exported, we test via the command's file analysis

// Helper: create a temp file and return its path
async function createTempFile(content, ext = '.js') {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'aid-test-'));
  const filePath = path.join(tmpDir, `test${ext}`);
  await fs.writeFile(filePath, content, 'utf-8');
  return { filePath, cleanup: () => fs.remove(tmpDir) };
}

// We need to extract the internal functions for direct testing
// Re-implement the pure logic functions based on analyze.js source

function detectAICode(content, lines) {
  const indicators = [];
  const aiPatterns = [
    { pattern: /\/\/ .* generated by/i, desc: 'AI 生成注释' },
    { pattern: /\/\/ auto-generated/i, desc: '自动生成标记' },
    { pattern: /TODO:.*implement/i, desc: '未实现的 TODO' },
    { pattern: /FIXME:/i, desc: 'FIXME 标记' },
  ];
  aiPatterns.forEach(({ pattern, desc }) => {
    if (pattern.test(content)) {
      indicators.push(desc);
    }
  });
  const codeLines = lines.filter(l => l.trim() && !l.trim().startsWith('//'));
  const uniqueLines = new Set(codeLines.map(l => l.trim()));
  const duplicateRatio = codeLines.length > 0 ? 1 - (uniqueLines.size / codeLines.length) : 0;
  if (duplicateRatio > 0.1) {
    indicators.push(`重复代码比例: ${(duplicateRatio * 100).toFixed(1)}%`);
  }
  return { detected: indicators.length > 0, indicators, duplicateRatio };
}

function analyzeQuality(content, lines, ext) {
  const issues = [];
  const metrics = {};
  const longLines = lines.filter(l => l.length > 120);
  if (longLines.length > 0) {
    issues.push({ type: 'style', message: `${longLines.length} 行超过 120 字符`, severity: 'warning' });
  }
  if (['.js', '.ts', '.jsx', '.tsx'].includes(ext)) {
    const functions = content.match(/function\s+\w+\s*\([^)]*\)\s*\{[\s\S]*?\n\}/g) || [];
    const longFunctions = functions.filter(f => f.split('\n').length > 50);
    if (longFunctions.length > 0) {
      issues.push({ type: 'complexity', message: `${longFunctions.length} 个函数超过 50 行`, severity: 'warning' });
    }
    metrics.functionCount = functions.length;
    metrics.avgFunctionLength = functions.length > 0
      ? functions.reduce((sum, f) => sum + f.split('\n').length, 0) / functions.length
      : 0;
  }
  const todos = (content.match(/TODO:/gi) || []).length;
  const fixmes = (content.match(/FIXME:/gi) || []).length;
  if (todos > 0 || fixmes > 0) {
    issues.push({ type: 'todos', message: `${todos} TODOs, ${fixmes} FIXMEs`, severity: 'info' });
  }
  return {
    score: Math.max(0, 100 - issues.filter(i => i.severity === 'warning').length * 10),
    issues,
    metrics
  };
}

function analyzeSecurity(content) {
  const vulnerabilities = [];
  const securityPatterns = [
    { pattern: /eval\s*\(/g, desc: 'eval() 使用 - 潜在代码注入风险', severity: 'high' },
    { pattern: /innerHTML\s*=/g, desc: 'innerHTML 赋值 - XSS 风险', severity: 'medium' },
    { pattern: /password\s*=\s*['"]/, desc: '硬编码密码', severity: 'high' },
    { pattern: /api[_-]?key\s*=\s*['"]/, desc: '硬编码 API key', severity: 'high' },
  ];
  securityPatterns.forEach(({ pattern, desc, severity }) => {
    const matches = content.match(pattern);
    if (matches) {
      vulnerabilities.push({ type: desc, severity, count: matches.length });
    }
  });
  return {
    secure: vulnerabilities.filter(v => v.severity === 'high').length === 0,
    vulnerabilities
  };
}

describe('analyzeCode - detectAICode', () => {
  test('detects AI-generated comments', () => {
    const content = '// This was generated by ChatGPT\nconst x = 1;';
    const lines = content.split('\n');
    const result = detectAICode(content, lines);
    expect(result.detected).toBe(true);
    expect(result.indicators).toContain('AI 生成注释');
  });

  test('detects auto-generated markers', () => {
    const content = '// auto-generated file\nconst x = 1;';
    const result = detectAICode(content, content.split('\n'));
    expect(result.detected).toBe(true);
    expect(result.indicators).toContain('自动生成标记');
  });

  test('detects FIXME markers', () => {
    const content = 'const x = 1; // FIXME: fix this later';
    const result = detectAICode(content, content.split('\n'));
    expect(result.detected).toBe(true);
    expect(result.indicators).toContain('FIXME 标记');
  });

  test('returns no indicators for clean code', () => {
    const content = 'const x = 1;\nconst y = 2;\nconsole.log(x + y);';
    const result = detectAICode(content, content.split('\n'));
    expect(result.detected).toBe(false);
    expect(result.indicators).toHaveLength(0);
  });

  test('detects high duplicate ratio', () => {
    const content = 'console.log("hello");\nconsole.log("hello");\nconsole.log("hello");\nconsole.log("hello");';
    const result = detectAICode(content, content.split('\n'));
    expect(result.duplicateRatio).toBeGreaterThan(0.1);
    expect(result.indicators.some(i => i.includes('重复代码比例'))).toBe(true);
  });

  test('handles empty content', () => {
    const result = detectAICode('', []);
    expect(result.detected).toBe(false);
    expect(result.duplicateRatio).toBe(0);
  });
});

describe('analyzeCode - analyzeQuality', () => {
  test('penalizes long lines', () => {
    const longLine = 'x'.repeat(150);
    const content = longLine;
    const result = analyzeQuality(content, content.split('\n'), '.js');
    expect(result.issues.some(i => i.type === 'style')).toBe(true);
    expect(result.score).toBeLessThan(100);
  });

  test('full score for clean code', () => {
    const content = 'const x = 1;\nconst y = 2;';
    const result = analyzeQuality(content, content.split('\n'), '.js');
    expect(result.score).toBe(100);
    expect(result.issues).toHaveLength(0);
  });

  test('detects TODOs and FIXMEs', () => {
    const content = 'const x = 1; // TODO: implement\n// FIXME: broken';
    const result = analyzeQuality(content, content.split('\n'), '.js');
    const todoIssue = result.issues.find(i => i.type === 'todos');
    expect(todoIssue).toBeDefined();
    expect(todoIssue.message).toContain('1 TODOs');
    expect(todoIssue.message).toContain('1 FIXMEs');
  });

  test('counts JS functions', () => {
    const content = 'function foo() {\n  return 1;\n}\nfunction bar() {\n  return 2;\n}';
    const result = analyzeQuality(content, content.split('\n'), '.js');
    expect(result.metrics.functionCount).toBeGreaterThanOrEqual(2);
  });

  test('handles non-JS files without function metrics', () => {
    const content = 'def foo():\n  pass';
    const result = analyzeQuality(content, content.split('\n'), '.py');
    expect(result.metrics.functionCount).toBeUndefined();
  });
});

describe('analyzeCode - analyzeSecurity', () => {
  test('detects eval() usage', () => {
    const content = 'eval(userInput);';
    const result = analyzeSecurity(content);
    expect(result.secure).toBe(false);
    expect(result.vulnerabilities[0].type).toContain('eval');
    expect(result.vulnerabilities[0].severity).toBe('high');
  });

  test('detects hardcoded passwords', () => {
    const content = "const password = 'admin123';";
    const result = analyzeSecurity(content);
    expect(result.secure).toBe(false);
    expect(result.vulnerabilities.some(v => v.type.includes('硬编码密码'))).toBe(true);
  });

  test('detects hardcoded API keys', () => {
    const content = 'const api_key = "sk-12345";';
    const result = analyzeSecurity(content);
    expect(result.secure).toBe(false);
    expect(result.vulnerabilities.some(v => v.type.includes('API key'))).toBe(true);
  });

  test('detects innerHTML XSS risk', () => {
    const content = 'element.innerHTML = data;';
    const result = analyzeSecurity(content);
    expect(result.vulnerabilities.some(v => v.severity === 'medium')).toBe(true);
  });

  test('returns secure for safe code', () => {
    const content = 'const x = 1;\nconsole.log(x);';
    const result = analyzeSecurity(content);
    expect(result.secure).toBe(true);
    expect(result.vulnerabilities).toHaveLength(0);
  });
});
