"""C591: temporal-bounded event-count faces — 60159905 + a3838d2b
(one mechanism, two constraint families).

Head 1: "How many dinner parties have I attended in the past
month?" Census (all 500): matches EXACTLY 60159905, unbanked WRONG
(gate=counting via enum_count → '1' today). Evidence (user lines,
verbatim): three attended instances inside answer sessions —
'Italian feast at Sarah's place last week' (s8), 'we had at Mike's
place two weeks ago' (s4), 'we had at Alex's place yesterday' (s4)
— distinct hosts {sarah, mike, alex} = 3 = GT 'three'. Decoys
structurally out: 'dinner party I'm hosting soon' (future framing,
no past marker, no at-place anchor), David's birthday party (s0
session carries no dinner-party topic word — session-topic gate),
assistant planning prose (user-role wall), own BBQs (no at-place
anchor).

Head 2: "How many charity events did I participate in before the
'Run for the Cure' event?" Census (all 500): matches EXACTLY
a3838d2b, unbanked WRONG ('1' today). Evidence (user lines,
verbatim): dated participation instances — 'Dance for a Cause'
May 1st (s24, consistent duplicate m8), 'charity golf tournament'
July 17th (s30, consistent duplicate m4), 'Walk for Wildlife' June
(s35, volunteered — charity signal via verb), 'Food for Thought'
gala September 25th (s37); anchor 'Run for the Cure' resolved to
October 15th from name+date lines (s12). Strictly-before count =
4 = GT. November 'Bike-a-Thon' (s33) is AFTER the anchor — the
temporal trap the strict month comparison excludes; 'considering
participating in a charity swim event' has no past-tense verb and
no date (structurally out); the concert (8cf0d2a9) has no charity
signal.

Guards pinned here:
- user-role wall (assistant prose never renders)
- future framing never renders (hosting soon / considering)
- session-topic gate for head 1 (dinner-party word must appear in
  the session's user lines — birthday-party session gated out)
- window discipline: relative markers carry bounded max-age;
  markers beyond the window cannot render
- anchor conflict → None; unresolvable evidence → None (falls
  through; enum_count keeps its remaining rows untouched)
- mechanism, not hardcoding: mutating dates/hosts moves the answer
- word-only render 'three' / 'four': judge_semantic banks these
  rows (frozen correct_exact=False), and _sem_norm folds number
  words - 'three'=='three' exact, 'four' norm-folds to GT '4'
"""
import os
import sys
import unittest

if os.environ.get("PYTHONHASHSEED") != "7":
    os.execve(sys.executable, [sys.executable] + sys.argv,
              {**os.environ, "PYTHONHASHSEED": "7"})

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from amg_bench_quality import (
    _cnt_event_count,
    answer_counting,
    counting_form,
)

Q_DINNER = 'How many dinner parties have I attended in the past month?'
Q_CHARITY = ("How many charity events did I participate in before "
             "the 'Run for the Cure' event?")

# ── verbatim dataset fixtures (generated by step3_gen_fixture.py;
#    drift pins assert dataset substrings still exist) ──

# ── verbatim 60159905 (dinner parties past month) ──
U_S4_M0 = "I'm looking for some new recipe ideas for a dinner party I'm hosting soon. Do you have any suggestions for a potluck theme, where everyone brings a dish from a different cuisine?"
U_S4_M2 = "I love these ideas! I'm definitely going to consider the Global Street Food theme. By the way, I've also had a great experience with a BBQ theme, like the one we had at Mike's place two weeks ago, where we watched a football game together. Do you have any BBQ recipe ideas that would fit well with the Global Street Food theme?"
U_S4_M4 = "That's great! I think I'll have a mix of grilled and non-grilled dishes to cater to different tastes. By the way, I've also had experience with dinner parties that are more low-key, like the ones we had at Alex's place yesterday, where we had a potluck and tried out different cuisines from around the world, and also at Mike's place, where we had a BBQ and watched a football game together. Do you have any tips on how to make the party more interactive and engaging for guests?"
A_S4_M5 = 'You\'re referring to creating a more immersive and engaging experience for your guests. I\'ve got some fantastic tips to help you achieve that:\n\n**Interactive Elements:**\n\n1. **Foodie Passport**: Create a "passport" for each guest, where they can get a stamp or signature from each dish they try. This encourages guests to explore different cuisines and interact with each other.\n2. **Global Music Playlist**: Curate a playlist featuring music from various countries and cultures to set the mood and create a festive atmosphere.\n3. **Cultural Trivia**: Prepare a list of trivia questions related to the different cuisines and cultures represented at the party. This can be a fun way to engage guests and spark conversations.\n4. **Food and Drink Pairing**: Offer pairing suggestions for each dish, such as wine, beer, or cocktails from the corresponding country or region. This adds an educational element and encourages guests to experiment with new flavors.\n5. **Guest Chef Stations**: Invite a few guests to act as "guest chefs" and have them prepare their dishes on-site. This can be a great way to encourage interaction and create a sense of community.\n\n**Engagement Strategies:**\n\n1. **Encourage Storytelling**: Ask guests to share stories or anecdotes about their dishes, such as the inspiration behind the recipe or a personal connection to the cuisine.\n2. **Foodie Networking**: Create a "foodie networking" area where guests can share their favorite recipes, cooking techniques, or restaurant recommendations.\n3. **Global Food Challenges**: Organize fun challenges, like a "spicy food challenge" or a "guess the ingredient" game, to keep guests engaged and entertained.\n4. **Photo Booth**: Set up a photo booth with props and backdrops inspired by different cultures. This can be a great way to capture memories and create social media-worthy moments.\n5. **Gratitude Station**: Set up a "gratitude station" where guests can write thank-you notes or share what they\'re grateful for about the evening. This can be a lovely way to foster a sense of community and appreciation.\n\n**Logistical Tips:**\n\n1. **Labeling and Signage**: Clearly label each dish with its country of origin, ingredients, and any dietary restrictions. This helps guests navigate the spread and makes it easier for them to ask questions.\n2. **Comfortable Seating**: Ensure there\'s ample seating and comfortable areas for guests to relax and socialize.\n3. **Timing**: Consider the flow of the evening and pace the food, drinks, and activities to keep guests engaged and entertained throughout the party.\n\nBy incorporating these interactive elements, engagement strategies, and logistical tips, you\'ll create a memorable and immersive experience for your guests. They\'ll appreciate the effort you put into creating a unique and enjoyable evening that celebrates the diversity of global cuisine!'
U_S8_M0 = "I'm looking for some Italian recipe ideas for a dinner party I'm hosting soon. I attended a lovely Italian feast at Sarah's place last week, and it inspired me to try out some new dishes. Do you have any recommendations for a beginner like me?"
U_S8_M2 = "That's a great list of recipes! I think I'll start with the Spaghetti Aglio e Olio and Chicken Parmesan. I've always loved the combination of garlic and olive oil. By the way, speaking of dinner parties, I've had a lovely experience at Sarah's place recently, where we played board games until late into the night after the Italian feast. Do you have any recommendations for board games that would be a good fit for a dinner party?"
A_S8_M1 = "Buon appetito! I'm thrilled to hear that Sarah's Italian feast inspired you to host your own dinner party. Italian cuisine is incredibly diverse and rich, so I'd be happy to help you with some recipe ideas perfect for a beginner.\n\nHere are some classic and delicious Italian dishes that are sure to impress your guests:\n\n**Appetizers (Antipasti)**\n\n1. Bruschetta: Grilled bread with fresh tomatoes, basil, garlic, and mozzarella cheese.\n2. Caprese Skewers: Fresh mozzarella, cherry tomatoes, and basil on toothpicks, drizzled with olive oil and balsamic glaze.\n\n**Primo (First Course)**\n\n1. Spaghetti Aglio e Olio: Spaghetti with garlic, olive oil, and red pepper flakes. Simple yet flavorful!\n2. Creamy Tomato Pasta Bake: A comforting, easy-to-make pasta dish with ground beef, tomato sauce, and mozzarella cheese.\n\n**Secondo (Main Course)**\n\n1. Chicken Parmesan: Breaded and fried chicken breasts topped with marinara sauce and melted mozzarella cheese, served with a side of pasta or garlic bread.\n2. Bistecca alla Fiorentina: Grilled steak served with roasted vegetables and garlic mashed potatoes.\n\n**Contorno (Side Dish)**\n\n1. Roasted Vegetables: Seasonal vegetables (e.g., zucchini, bell peppers, cherry tomatoes) tossed with olive oil, salt, and pepper, then roasted to perfection.\n2. Garlic and Herb Roasted Potatoes: Thinly sliced potatoes tossed with olive oil, minced garlic, and chopped fresh herbs (e.g., rosemary, thyme).\n\n**Dolce (Dessert)**\n\n1. Tiramisù: Ladyfingers soaked in coffee and liqueur, layered with mascarpone cheese and cocoa powder.\n2. Panna Cotta: Creamy vanilla pudding topped with mixed berries and a drizzle of honey.\n\n**Tips and Essentials**\n\n* Use high-quality ingredients, such as fresh produce, good olive oil, and authentic Italian cheeses (e.g., Parmigiano-Reggiano, Mozzarella di Bufala).\n* Don't be afraid to simplify recipes or use store-bought shortcuts (e.g., pre-made pasta sauce, pre-breaded chicken cutlets).\n* Consider a buffet-style dinner to encourage socializing and make serving easier.\n* Pair your dishes with a selection of Italian wines, such as Pinot Grigio, Chianti, or Prosecco.\n\nBuon appetito, and I hope your dinner party is a huge success!"
U_S0_M0 = "I'm planning a movie night with friends next week and I want to pick a movie that everyone will enjoy. Can you suggest some popular movies from the past year that are good for a group? By the way, I just got back from a birthday party for my colleague and friend, David, last week, and it was amazing - we had a blast playing laser tag and singing karaoke!"
# ── verbatim a3838d2b (charity before Run for the Cure) ──
U_ANCHOR = 'I\'m looking for some tips on how to stay motivated to continue participating in charity events. I just ran 5 kilometers in the "Run for the Cure" event on October 15th and raised $250 for breast cancer research, which was an amazing experience.'
U_ANCHOR_B = 'That\'s really helpful, thanks! I\'ve been meaning to get back into cycling for a while now, and this gives me a good starting point. By the way, I just got back from the "Run for the Cure" event on October 15th, where I ran 5 kilometers to raise money for breast cancer research. It was an incredible experience, and I\'m looking forward to doing more charity events in the future.'
U_DANCE = 'I\'m looking for some information on local charity events happening in the next few months. I\'ve been really active in the charity scene lately, actually - I just participated in the "Dance for a Cause" event on May 1st, which was a blast. Do you know of any upcoming events that I might be interested in?'
U_DANCE_DUP = 'I\'ve actually already participated in a dance marathon, the "Dance for a Cause" event on May 1st, where I danced for 6 hours to raise money for a local arts program. It was an amazing experience, and I\'m looking for more opportunities like that. Can you suggest any other events or organizations that combine arts and fitness?'
U_GOLF = "Hi! I'm looking for some advice on how to improve my golf game. I attended a charity golf tournament on July 17th, and while I had a blast playing with colleagues, I realized I need to work on my swing. Do you have any tips or recommendations for a beginner like me?"
U_GOLF_DUP = "I'll definitely check out those resources. I'm also thinking of organizing a charity golf tournament similar to the one I attended on July 17th. Do you have any tips or advice on how to plan and organize a successful charity golf tournament?"
U_BIKE = 'I\'m looking to find some local bike trails for a casual ride this weekend. Do you have any recommendations? By the way, I recently participated in the "Bike-a-Thon" charity event in November, which was a lot of fun and a great way to support a good cause.'
U_WILDLIFE = "I'm looking for some information on wildlife conservation efforts in my area. I've been interested in this topic since I volunteered at the Walk for Wildlife event in June, where we raised awareness and funds for conservation efforts. Do you know of any organizations or initiatives that I can get involved with?"
U_GALA = 'I\'m looking for some information on local charity events happening in the next few months. I\'ve been involved in a few events recently, actually - I volunteered at the "Food for Thought" charity gala on September 25th, which was a great experience. Do you know of any upcoming events that focus on food banks or hunger relief?'
U_SWIM = 'The "Run for the Cure" event was truly inspiring, and I think what resonated with me the most was seeing so many people come together for a common cause. There were over 5,000 participants, and the energy was electric! Crossing the finish line and knowing that I\'d raised $250 for breast cancer research was an incredible feeling.\n\nAs for future charity events, I\'m actually interested in exploring more cycling events, as I mentioned earlier. I\'ve also been considering participating in a charity swim event to support a local children\'s hospital. I\'ve never done a swim event before, but I\'m excited to challenge myself and learn something new.\n\nWhat about you? Do you have any recommendations for charity events or causes that I might be interested in?'
U_CONCERT = 'I actually attended a concert at the Forum recently, it was Billie Eilish and it was amazing!'

# ── drift pins: dataset drift must fail loudly ──
assert "at Mike's place two weeks ago" in U_S4_M2, "U_S4_M2 drifted"
assert "at Alex's place yesterday" in U_S4_M4, "U_S4_M4 drifted"
assert "Italian feast at Sarah's place last week" in U_S8_M0, "U_S8_M0 drifted"
assert 'hosting soon' in U_S8_M0, "U_S8_M0 drifted"
assert 'birthday party' in U_S0_M0, "U_S0_M0 drifted"
assert '"Run for the Cure" event on October 15th' in U_ANCHOR, "U_ANCHOR drifted"
assert '"Dance for a Cause" event on May 1st' in U_DANCE, "U_DANCE drifted"
assert 'charity golf tournament on July 17th' in U_GOLF, "U_GOLF drifted"
assert '"Bike-a-Thon" charity event in November' in U_BIKE, "U_BIKE drifted"
assert 'Walk for Wildlife event in June' in U_WILDLIFE, "U_WILDLIFE drifted"
assert '"Food for Thought" charity gala on September 25th' in U_GALA, "U_GALA drifted"
assert 'charity swim event' in U_SWIM, "U_SWIM drifted"
assert 'concert at the Forum' in U_CONCERT, "U_CONCERT drifted"



def sess(*turns):
    return [{"session_id": "session_1", "turns": list(turns)}]


def multi(*sessions):
    return [{"session_id": f"session_{i+1}", "turns": list(t)}
            for i, t in enumerate(sessions)]


def u(text):
    return {"role": "user", "content": text}


def a(text):
    return {"role": "assistant", "content": text}


DINNER_REAL = multi(
    [u(U_S0_M0)],                                    # birthday decoy sess
    [u(U_S4_M0), u(U_S4_M2), u(U_S4_M4), a(A_S4_M5)],
    [u(U_S8_M0), a(A_S8_M1), u(U_S8_M2)],
)

DINNER_NO_GATE = multi(
    [u(U_S0_M0)],                                    # no dinner-party topic
    [u(U_S4_M2), u(U_S4_M4)],
)

CHARITY_REAL = multi(
    [u(U_ANCHOR), u(U_ANCHOR_B), a("Some advice."), u(U_SWIM)],
    [u(U_DANCE), a("Great cause!"), u(U_DANCE_DUP)],
    [u(U_GOLF), u(U_GOLF_DUP)],
    [u(U_BIKE)],
    [u(U_WILDLIFE)],
    [u(U_GALA)],
    [u(U_CONCERT)],                                  # non-charity decoy
)

CHARITY_NO_ANCHOR = multi(
    [u(U_DANCE), u(U_GOLF), u(U_WILDLIFE), u(U_GALA), u(U_BIKE)],
)

# ── form ──


class TestForm(unittest.TestCase):

    def test_form_dinner_head(self):
        self.assertEqual(counting_form(Q_DINNER), "event_count")

    def test_form_charity_head(self):
        self.assertEqual(counting_form(Q_CHARITY), "event_count")

    def test_other_forms_untouched(self):
        # non-counting questions stay unclaimed; the banked C590
        # coord_sum claim is not shadowed by the new gate
        self.assertIsNone(counting_form(
            'What did the mentor say about balancing risk and caution?'))
        self.assertEqual(
            counting_form('How many rare items do I have in total?'),
            'coord_sum')
        self.assertIsNone(_cnt_event_count(
            'How many books are in your apartment?', []))


# ── head 1: dinner parties past month ──


class TestDinnerHead(unittest.TestCase):

    def test_real_fixture_three(self):
        self.assertEqual(_cnt_event_count(Q_DINNER, DINNER_REAL),
                         'three')

    def test_answer_counting_contract(self):
        ans, detail = answer_counting(Q_DINNER, DINNER_REAL)
        self.assertEqual(ans, 'three')
        self.assertEqual(detail.get('form'), 'event_count')

    def test_host_dedup(self):
        # Sarah mentioned twice (last week + recently) still ONE party
        self.assertEqual(_cnt_event_count(Q_DINNER, multi(
            [u(U_S4_M0), u(U_S4_M2), u(U_S4_M4)],
            [u(U_S8_M0), u(U_S8_M2)])), 'three')

    def test_session_topic_gate(self):
        # a session whose user lines carry NO dinner-party topic
        # word is gated out even with a literal had-at line —
        # this is what kills David's birthday session (s0)
        self.assertIsNone(_cnt_event_count(Q_DINNER, multi(
            [u(U_S0_M0)],
            [u("we had at Chris's place last week, great times")])))

    def test_future_hosting_never_renders(self):
        # hosting-soon + recency-only lines carry no bounded marker
        # → no attended instance resolves (U_S8_M2: 'recently' and
        # a verb-less feast recall — both structurally out)
        self.assertIsNone(_cnt_event_count(Q_DINNER, multi(
            [u(U_S4_M0)], [u(U_S8_M2)])))

    def test_window_discipline(self):
        # 'two weeks ago' (14d) is inside the past-month window;
        # push the markers past it via a mutated fixture and the
        # instance must drop
        old = u("we had at Mike's place six weeks ago, great BBQ")
        self.assertEqual(_cnt_event_count(Q_DINNER, multi(
            [u(U_S4_M0), old], [u(U_S8_M0), u(U_S4_M4)])), 'two')

    def test_assistant_wall(self):
        # the assistant echo of the feast must not add an instance
        self.assertEqual(_cnt_event_count(Q_DINNER, multi(
            [u(U_S4_M0), u(U_S4_M2), u(U_S4_M4), a(A_S4_M5)],
            [u(U_S8_M0), a(A_S8_M1), u(U_S8_M2), a(A_S8_M1)])),
            'three')

    def test_mechanism_not_hardcoded_host(self):
        mutated = u(U_S4_M2.replace("Mike's", "Norbert's"))
        self.assertEqual(_cnt_event_count(Q_DINNER, multi(
            [u(U_S4_M0), mutated, u(U_S4_M4)],
            [u(U_S8_M0)])), 'three')


# ── head 2: charity events before the anchor ──


class TestCharityHead(unittest.TestCase):

    def test_real_fixture_four(self):
        self.assertEqual(_cnt_event_count(Q_CHARITY, CHARITY_REAL),
                         'four')

    def test_answer_counting_contract(self):
        ans, detail = answer_counting(Q_CHARITY, CHARITY_REAL)
        self.assertEqual(ans, 'four')
        self.assertEqual(detail.get('form'), 'event_count')

    def test_november_trap_excluded(self):
        # the Bike-a-Thon line alone must never render as a before-
        # count; without other instances nothing resolves
        self.assertIsNone(_cnt_event_count(Q_CHARITY, multi([u(U_BIKE)])))

    def test_anchor_line_not_counted(self):
        # anchor-name instances are structurally excluded: only the
        # four pre-anchor events count, the Oct 15 run never does
        self.assertEqual(_cnt_event_count(Q_CHARITY, multi(
            [u(U_ANCHOR), u(U_DANCE)])), 'one')

    def test_future_considering_never_renders(self):
        self.assertIsNone(_cnt_event_count(Q_CHARITY, multi([u(U_SWIM)])))

    def test_concert_not_charity(self):
        self.assertIsNone(_cnt_event_count(
            Q_CHARITY, multi([u(U_CONCERT), u(U_ANCHOR)])))

    def test_consistent_duplicate_dedup(self):
        self.assertEqual(_cnt_event_count(Q_CHARITY, multi(
            [u(U_DANCE), u(U_DANCE_DUP)], [u(U_ANCHOR)])), 'one')

    def test_missing_anchor_falls_through(self):
        # no anchor date resolvable → None (fall-through, not '4')
        self.assertIsNone(_cnt_event_count(
            Q_CHARITY, CHARITY_NO_ANCHOR))

    def test_mechanism_not_hardcoded_date(self):
        # moving Dance for a Cause past the anchor drops it
        mutated = u(U_DANCE.replace("May 1st", "December 1st"))
        self.assertEqual(_cnt_event_count(Q_CHARITY, multi(
            [u(U_ANCHOR)], [mutated], [u(U_GOLF)], [u(U_WILDLIFE)],
            [u(U_GALA)], [u(U_BIKE)])), 'three')


# ── judge ──


class TestJudge(unittest.TestCase):

    def test_gt_word_form_matches(self):
        from amg_bench_quality import judge_semantic
        self.assertEqual(judge_semantic(Q_DINNER, 'three', 'three'),
                         'CORRECT')

    def test_gt_digit_form_matches(self):
        # GT '4' is a digit; the word render norm-folds to it
        from amg_bench_quality import judge_semantic
        self.assertEqual(judge_semantic(Q_CHARITY, 'four', '4'),
                         'CORRECT')

    def test_wrong_count_rejected(self):
        from amg_bench_quality import judge_semantic
        self.assertNotEqual(judge_semantic(Q_CHARITY, 'five', '4'),
                            'CORRECT')
        self.assertNotEqual(judge_semantic(Q_DINNER, 'one', 'three'),
                            'CORRECT')


if __name__ == '__main__':
    unittest.main()
