"""C592: temporal-bounded acquisition-count faces — 3a704032 +
9d25d4e0 (one mechanism, two constraint families).

Head 1: "How many plants did I acquire in the last month?" Census
(all 500): matches EXACTLY 3a704032, unbanked (gate != counting
today — the row fell through to chit-chat). Evidence (user lines,
verbatim): peace lily + succulent (nursery, 'two weeks ago', s1)
and snake plant (sister, 'last month', s16) = 3 = GT. Decoys
structurally out: 'recommend a good fertilizer for my snake plant
and succulent' (no acquisition verb), 'glad I got some helpful
tips for my peace lily' (verb, no marker), 'plant tracking app'
(no verb, no marker), 'water my plants, which I got...' (bare
'plants' is a CATEGORY word — the C519 lesson — never an item),
basil/fern mentions (no verb+marker).

Head 2: "How many pieces of jewelry did I acquire in the last two
months?" Census (all 500): matches EXACTLY 9d25d4e0, unbanked
(same). Evidence (user lines, verbatim): flea-market earrings
('last weekend', s6), silver necklace ('the 15th of last month',
s30), engagement ring ('a month ago', s33) = 3 = GT. Decoys
structurally out: 'locate a pair of earrings that I think I left
at my cousin's place' (no acquisition verb — and the grandma-
gifted pair carries no marker), 'clean my gold chains and rings'
(cleaning question, no verb+marker), 'getting a jewelry cleaning
kit' ('getting' is not an acquisition verb), assistant planning
prose (user-role wall). Item keys are HEAD NOUNS: 'new pair of
earrings' and 'those emerald earrings' collapse to one item;
'a small pendant' is a with-clause modifier of the necklace —
'pendant' is not a countable head.

Guards pinned here:
- form claim: counting_form returns 'acquire' for both heads and
  does NOT steal 4f54b7c9 ('antique items ... inherit or acquire
  from my family members' — no 'in the last' window — stays with
  enum_count)
- user-role wall (assistant prose never renders)
- session-topic gate (session whose user lines never name the
  topic contributes nothing — the C586/C591 lesson at session
  grain)
- window discipline: relative markers carry bounded max-age
  ('last month' = 31 fits the month window; 'six weeks ago' = 42
  does not; 'three months ago' = 90 fits a three-month window);
  markers beyond the window cannot render
- dedup discipline: repeat mentions of the same item count once
  ('succulent plant' folds to 'succulent'); bare 'plants' never
  counts
- mechanism, not hardcoding: mutating markers/items moves the
  answer
- word-only render 'three': judge_semantic banks these rows
  (frozen correct_exact=False), and _sem_norm folds number words
  — 'three' matches GT '3' (norm fold)
"""
import os
import sys
import unittest

if os.environ.get("PYTHONHASHSEED") != "7":
    os.execve(sys.executable, [sys.executable] + sys.argv,
              {**os.environ, "PYTHONHASHSEED": "7"})

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from amg_bench_quality import (
    _cnt_acquire,
    answer_counting,
    counting_form,
)

Q_PLANTS = 'How many plants did I acquire in the last month?'
Q_JEWEL = ('How many pieces of jewelry did I acquire in the last '
           'two months?')
Q_ANTIQUE = ('How many antique items did I inherit or acquire from '
             'my family members?')

# ── verbatim dataset fixtures (generated by step3_gen_fixture.py;
#    drift pins assert dataset substrings still exist) ──

# ── verbatim 3a704032 (plants acquired last month) ──
U_S2_A = "I'm trying to figure out the best way to care for my peace lily, which I got from the nursery two weeks ago along with a succulent. It's been losing some leaves, but I've read that's normal. Do you have any general tips for keeping it healthy?"
U_S2_B = "I actually use a mixture of water and fertilizer when I water my plants, which I got from the nursery where I bought the peace lily and a succulent plant two weeks ago. Do you think that's okay to use for my peace lily, or should I switch to a balanced fertilizer?"
U_S17_A = "I'm also wondering if I should repot my snake plant, which I got from my sister last month. Do you think it would benefit from a bigger pot and some fresh potting mix?"
U_S14_A = "I'm also wondering if you can recommend a good fertilizer for my snake plant and succulent? I've been using a general-purpose fertilizer, but I'm not sure if they need something more specific."
U_S2_C = "I'm glad I got some helpful tips for my peace lily. I also wanted to ask, what's the ideal temperature range for my peace lily? I've been keeping it in a spot with a consistent temperature between 65°F to 70°F (18°C to 21°C), but I'm not sure if that's suitable."
U_S2_D = "I've been using a plant tracking app to keep track of my watering schedule and fertilization reminders, which has been really helpful. Do you have any recommendations for how often I should water my peace lily, considering I'm already using a mixture of water and fertilizer when I water?"

# ── verbatim 9d25d4e0 (jewelry acquired last two months) ──
U_S7_A = "I'm thinking of cleaning my jewelry collection this weekend and I'm not sure what's the best way to clean different types of jewelry. Do you have any tips or recommendations? By the way, I just got a new pair of earrings last weekend at a flea market - a stunning pair of emerald earrings that I'm absolutely loving!"
U_S7_B = "I'm thinking of getting a jewelry cleaning kit that includes a solution and a soft cloth. Do you think that would be a good idea? And by the way, I'm really glad I got those emerald earrings at the flea market last weekend - they're really stunning!"
U_S31_A = "I'm thinking of cleaning my jewelry collection and I want to make sure I do it right. Can you guide me through the process or recommend a good jewelry cleaning solution? By the way, I just got a new silver necklace with a small pendant on the 15th of last month, and I want to make sure I take good care of it."
U_S31_B = "I'm also trying to locate a pair of earrings that I think I left at my cousin's place after wearing them to her birthday party. They're a special pair with little diamonds that my grandma gave me. Do you have any tips on how to keep track of my jewelry when I'm traveling or lending them to others?"
U_S34_A = "I need help with cleaning my jewelry. Can you give me some tips on how to properly clean my gold chains and rings? Oh, and by the way, I got my engagement ring a month ago, and I still need to get it resized - it's still a bit too loose."

# ── drift pins: dataset drift must fail loudly ──
assert "peace lily, which I got from the nursery two weeks ago" in U_S2_A
assert "a succulent." in U_S2_A, "U_S2_A drifted"
assert "I bought the peace lily and a succulent plant two weeks ago" \
    in U_S2_B, "U_S2_B drifted"
assert "water my plants, which I got from the nursery" in U_S2_B, \
    "U_S2_B drifted"
assert "repot my snake plant, which I got from my sister last month" \
    in U_S17_A, "U_S17_A drifted"
assert "recommend a good fertilizer for my snake plant and succulent" \
    in U_S14_A, "U_S14_A drifted"
assert "glad I got some helpful tips for my peace lily" in U_S2_C, \
    "U_S2_C drifted"
assert "plant tracking app" in U_S2_D, "U_S2_D drifted"
assert "just got a new pair of earrings last weekend at a flea market" \
    in U_S7_A, "U_S7_A drifted"
assert "got those emerald earrings at the flea market last weekend" \
    in U_S7_B, "U_S7_B drifted"
assert "getting a jewelry cleaning kit" in U_S7_B, "U_S7_B drifted"
assert "new silver necklace with a small pendant on the 15th of last " \
    "month" in U_S31_A, "U_S31_A drifted"
assert "left at my cousin's place" in U_S31_B, "U_S31_B drifted"
assert "my grandma gave me" in U_S31_B, "U_S31_B drifted"
assert "got my engagement ring a month ago" in U_S34_A, "U_S34_A drifted"
assert "clean my gold chains and rings" in U_S34_A, "U_S34_A drifted"


def S(sid, *user_texts):
    return {"session_id": sid,
            "turns": [{"role": "user", "content": t} for t in user_texts]}


PLANTS_SESSIONS = [
    S("session_2", U_S2_A, U_S2_B),
    S("session_14", U_S14_A),
    S("session_17", U_S17_A, U_S2_C, U_S2_D),
]
JEWEL_SESSIONS = [
    S("session_7", U_S7_A, U_S7_B),
    S("session_31", U_S31_A, U_S31_B),
    S("session_34", U_S34_A),
]


class TestAcquireFace(unittest.TestCase):

    # ── form claim ──

    def test_form_claim_both_heads(self):
        self.assertEqual(counting_form(Q_PLANTS), "acquire")
        self.assertEqual(counting_form(Q_JEWEL), "acquire")

    def test_form_does_not_steal_antique_head(self):
        # 4f54b7c9 has no 'in the last <period>' window — it must
        # stay with enum_count (census: distinct row, unbanked,
        # future cycle)
        self.assertEqual(counting_form(Q_ANTIQUE), "enum_count")

    def test_form_non_window_variants_unclaimed(self):
        # behavior-neutral: without the 'in the last <period>'
        # window these variants stay exactly where they were
        # (enum_count claims plain how-many forms)
        self.assertEqual(counting_form(
            'How many plants did I acquire from the nursery?'),
            "enum_count")
        self.assertEqual(counting_form('How many plants do I own?'),
                         "enum_count")

    # ── the two faces, end to end ──

    def test_plants_three(self):
        self.assertEqual(_cnt_acquire(Q_PLANTS, PLANTS_SESSIONS),
                         "three")

    def test_jewelry_three(self):
        self.assertEqual(_cnt_acquire(Q_JEWEL, JEWEL_SESSIONS), "three")

    def test_answer_counting_form_meta(self):
        self.assertEqual(answer_counting(Q_PLANTS, PLANTS_SESSIONS),
                         ("three", {"form": "acquire"}))
        self.assertEqual(answer_counting(Q_JEWEL, JEWEL_SESSIONS),
                         ("three", {"form": "acquire"}))

    # ── dedup / category discipline ──

    def test_repeat_mention_counts_once(self):
        # drop the s1 rephrase — the nursery pair still counts via
        # turn 1 only (peace lily + succulent), snake plant via s16
        sessions = [S("session_2", U_S2_A),
                    S("session_14", U_S14_A),
                    S("session_17", U_S17_A)]
        self.assertEqual(_cnt_acquire(Q_PLANTS, sessions), "three")

    def test_bare_plants_is_category_word(self):
        # 'water my plants, which I got from the nursery' carries
        # verb + marker + the generic category noun — it must add
        # NO item (the two specific NPs in the same sentence still
        # do); with ONLY the generic surface the count is empty
        generic_only = ("I water my plants, which I got from the "
                        "nursery two weeks ago. They seem healthy.")
        sessions = [S("session_2", generic_only)]
        self.assertIsNone(_cnt_acquire(Q_PLANTS, sessions))

    # ── decoys, structurally out ──

    def test_plants_decoys_only_none(self):
        # fertilizer ask (no verb), helpful-tips (no marker),
        # tracking app (no verb, no marker)
        sessions = [S("session_14", U_S14_A),
                    S("session_17", U_S2_C, U_S2_D)]
        self.assertIsNone(_cnt_acquire(Q_PLANTS, sessions))

    def test_jewelry_decoys_only_none(self):
        # locate/left (no acquisition verb), grandma gift (no
        # marker), cleaning asks, cleaning kit ('getting') — the
        # legitimate flea-market dup sentence is stripped from
        # U_S7_B (it would rightly count as the earring)
        kit_only = ("I'm thinking of getting a jewelry cleaning kit "
                    "that includes a solution and a soft cloth. Do "
                    "you think that would be a good idea?")
        sessions = [S("session_31", U_S31_B),
                    S("session_34", U_S34_A.replace(
                        "Oh, and by the way, I got my engagement ring"
                        " a month ago, and I still need to get it "
                        "resized - it's still a bit too loose.", "")),
                    S("session_7", kit_only)]
        self.assertIsNone(_cnt_acquire(Q_JEWEL, sessions))

    def test_off_topic_session_gated(self):
        # verb + marker + $ outside any topic session: neither the
        # session-topic gate nor the NP lexicon admits it
        sessions = [S("session_99",
                      "I got a new laptop bag on Amazon for $39.99 on "
                      "February 20th, and it's been great.")]
        self.assertIsNone(_cnt_acquire(Q_JEWEL, sessions))
        self.assertIsNone(_cnt_acquire(Q_PLANTS, sessions))

    def test_user_role_wall(self):
        self.assertIsNone(_cnt_acquire(
            Q_PLANTS, [{"session_id": "session_2", "turns": [
                {"role": "assistant", "content": U_S2_A}]}]))
        self.assertIsNone(_cnt_acquire(
            Q_JEWEL, [{"session_id": "session_7", "turns": [
                {"role": "assistant", "content": U_S7_A}]}]))

    def test_empty_sessions_none(self):
        self.assertIsNone(_cnt_acquire(Q_PLANTS, []))
        self.assertIsNone(_cnt_acquire(Q_JEWEL, []))

    # ── mechanism, not hardcoding ──

    def test_marker_beyond_window_moves_answer(self):
        sessions = [S("session_2", U_S2_A, U_S2_B),
                    S("session_17", U_S17_A.replace(
                        "last month", "last year"))]
        self.assertEqual(_cnt_acquire(Q_PLANTS, sessions), "two")

    def test_all_markers_beyond_window_none(self):
        sessions = [S("session_2", U_S2_A.replace(
            "two weeks ago", "six weeks ago")),
            S("session_17", U_S17_A.replace(
                "last month", "six months ago"))]
        self.assertIsNone(_cnt_acquire(Q_PLANTS, sessions))

    def test_window_parses_number_words(self):
        # 'three months ago' (90d) fits a three-month window (91d)
        sessions = [S("s", "I bought a fern three months ago.")]
        self.assertEqual(_cnt_acquire(
            "How many plants did I acquire in the last three months?",
            sessions), "one")
        # ...but not a one-month window (31d)
        self.assertIsNone(_cnt_acquire(Q_PLANTS, sessions))

    def test_unknown_period_falls_through(self):
        self.assertIsNone(_cnt_acquire(
            "How many plants did I acquire in the last bunch?", []))

    def test_unrelated_topic_mode_falls_through(self):
        # the form matches but neither topic face claims the NP
        self.assertIsNone(_cnt_acquire(
            "How many clocks did I acquire in the last month?",
            [S("s", "I got a cuckoo clock last week.")]))

    # ── render discipline ──

    def test_render_is_word_form(self):
        # word-only render: the replay harness banks through
        # judge_semantic (_sem_norm folds 'three' → GT '3')
        for ans in (_cnt_acquire(Q_PLANTS, PLANTS_SESSIONS),
                    _cnt_acquire(Q_JEWEL, JEWEL_SESSIONS)):
            self.assertEqual(ans, "three")
            self.assertNotIn(str(3), ans)


if __name__ == "__main__":
    unittest.main()
