import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── 模板定义 ──────────────────────────────────────────────
const TEMPLATES = {
  basic: {
    description: '基础 skill — 单文件，适合简单任务',
    files: ['SKILL.md'],
    dirs: [],
  },
  api: {
    description: 'API 集成 skill — 包含认证、请求封装、错误处理',
    files: ['SKILL.md'],
    dirs: ['references', 'scripts'],
  },
  mcp: {
    description: 'MCP Server skill — Model Context Protocol 工具服务',
    files: ['SKILL.md'],
    dirs: ['scripts'],
  },
  coding: {
    description: '编码辅助 skill — 代码生成、重构、审查',
    files: ['SKILL.md'],
    dirs: ['references', 'scripts'],
  },
};

// ── SKILL.md 模板 ─────────────────────────────────────────
function generateSkillMd(name, description, template) {
  const desc = description || `${name} skill`;
  const triggerMap = {
    basic: `Activate when user asks about ${name} or needs ${name}-related help.`,
    api: `Activate when user mentions ${name} API, needs to call ${name}, or integrate with ${name}.`,
    mcp: `Activate when user needs MCP tools for ${name} or asks to use ${name} via Model Context Protocol.`,
    coding: `Activate when user asks to write/refactor/review code related to ${name}.`,
  };

  let extra = '';
  if (template === 'api') {
    extra = `
## API Reference

| Endpoint | Method | Description |
|----------|--------|-------------|
| \`/api/v1/\` | GET | Example endpoint |

## Authentication

Set environment variable:
\`\`\`bash
export ${name.toUpperCase()}_API_KEY="your-key-here"
\`\`\`

## Error Handling

- Rate limits: respect Retry-After header
- Auth errors: surface clear message, suggest re-auth
- Network errors: retry with backoff (max 3)
`;
  } else if (template === 'mcp') {
    extra = `
## MCP Tools

### \`tool_name\`
- **Description**: What this tool does
- **Parameters**: \`{ param: type }\`
- **Returns**: Description of return value

## Setup

\`\`\`bash
# In mcporter config
{
  "${name}": {
    "command": "node",
    "args": ["scripts/server.js"]
  }
}
\`\`\`
`;
  } else if (template === 'coding') {
    extra = `
## Code Patterns

### Pattern: Example Pattern
Description of when and how to use this pattern.

\`\`\`javascript
// Example code
\`\`\`

## Style Guide

- Follow existing project conventions
- Prefer readability over cleverness
- Add inline comments for complex logic
`;
  }

  return `# ${name}

${desc}

## Activation
${triggerMap[template]}

## Usage

When this skill is activated:

1. **Understand** the user's request
2. **Plan** the approach
3. **Execute** using available tools
4. **Verify** the result
${extra}
## Notes

- Keep responses concise and actionable
- Ask for clarification when ambiguous
- Log important decisions for context

---
_Generated by skill-scaffolder on ${new Date().toISOString().split('T')[0]}_
`;
}

// ── 核心函数 ──────────────────────────────────────────────
export async function createSkill(name, options) {
  const template = options.template || 'basic';
  if (!TEMPLATES[template]) {
    throw new Error(`未知模板: ${template}. 可用: ${Object.keys(TEMPLATES).join(', ')}`);
  }

  const tpl = TEMPLATES[template];
  const outputDir = path.resolve(options.output, name);

  // 检查是否已存在
  try {
    await fs.access(outputDir);
    throw new Error(`目录已存在: ${outputDir}`);
  } catch (e) {
    if (e.message.startsWith('目录已存在')) throw e;
  }

  const dirs = [...tpl.dirs];
  if (options.withReferences && !dirs.includes('references')) dirs.push('references');
  if (options.withScripts && !dirs.includes('scripts')) dirs.push('scripts');

  const createdFiles = [];

  // 创建目录
  await fs.mkdir(outputDir, { recursive: true });
  for (const dir of dirs) {
    await fs.mkdir(path.join(outputDir, dir), { recursive: true });
    createdFiles.push(`${dir}/`);
  }

  // 生成 SKILL.md
  const skillMd = generateSkillMd(name, options.description, template);
  await fs.writeFile(path.join(outputDir, 'SKILL.md'), skillMd);
  createdFiles.push('SKILL.md');

  // 为 scripts/ 目录添加示例
  if (dirs.includes('scripts')) {
    const scriptContent = `#!/usr/bin/env node
// ${name} - helper script
// Usage: node scripts/helper.js [args]

console.log('Hello from ${name}!');
`;
    await fs.writeFile(path.join(outputDir, 'scripts', 'helper.js'), scriptContent);
    createdFiles.push('scripts/helper.js');
  }

  // 为 references/ 目录添加占位
  if (dirs.includes('references')) {
    const readme = `# ${name} References

Place reference documents, API docs, or examples here.
`;
    await fs.writeFile(path.join(outputDir, 'references', 'README.md'), readme);
    createdFiles.push('references/README.md');
  }

  return { path: outputDir, files: createdFiles };
}

export function listTemplates() {
  return Object.entries(TEMPLATES).map(([name, tpl]) => ({
    name,
    description: tpl.description,
  }));
}

export async function validateSkill(skillPath) {
  const resolved = path.resolve(skillPath);
  const issues = [];

  // 检查 SKILL.md
  const skillMd = path.join(resolved, 'SKILL.md');
  try {
    await fs.access(skillMd);
    const content = await fs.readFile(skillMd, 'utf-8');
    if (!content.includes('## Activation')) {
      issues.push('SKILL.md 缺少 ## Activation 部分');
    }
  } catch {
    issues.push('缺少 SKILL.md — 这是 skill 的必需文件');
  }

  // 检查目录命名
  const base = path.basename(resolved);
  if (base !== base.toLowerCase().replace(/\s+/g, '-')) {
    issues.push('目录名应使用 kebab-case (小写+连字符)');
  }

  // 检查 references 和 scripts
  for (const dir of ['references', 'scripts']) {
    const dirPath = path.join(resolved, dir);
    try {
      await fs.access(dirPath);
      const files = await fs.readdir(dirPath);
      if (files.length === 0) {
        issues.push(`${dir}/ 目录为空 — 考虑添加内容或删除`);
      }
    } catch {}
  }

  return { valid: issues.length === 0, issues };
}
