import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import ora from 'ora';

export default async function analyzeCommand(file, options) {
  console.log(chalk.bold('\n🔍 代码分析\n'));
  
  const targetPath = path.resolve(file);
  
  if (!(await fs.pathExists(targetPath))) {
    console.log(chalk.red(`路径不存在: ${targetPath}\n`));
    return;
  }
  
  const spinner = ora('分析中...').start();
  
  try {
    const stats = await fs.stat(targetPath);
    let results;
    
    if (stats.isDirectory()) {
      results = await analyzeDirectory(targetPath, options);
    } else {
      results = await analyzeFile(targetPath, options);
    }
    
    spinner.succeed('分析完成');
    
    // 输出结果
    await outputResults(results, options);
    
  } catch (error) {
    spinner.fail(chalk.red(`分析失败: ${error.message}`));
  }
}

async function analyzeDirectory(dirPath, options) {
  const results = {
    files: [],
    summary: {
      totalFiles: 0,
      totalLines: 0,
      totalFunctions: 0,
      issues: []
    }
  };
  
  const files = await getFiles(dirPath, options.type);
  
  for (const file of files) {
    const fileResult = await analyzeFile(file, options);
    results.files.push(fileResult);
    results.summary.totalFiles++;
    results.summary.totalLines += fileResult.lines || 0;
    results.summary.totalFunctions += fileResult.functions?.length || 0;
    if (fileResult.issues) {
      results.summary.issues.push(...fileResult.issues);
    }
  }
  
  return results;
}

async function analyzeFile(filePath, options) {
  const ext = path.extname(filePath);
  const content = await fs.readFile(filePath, 'utf-8');
  const lines = content.split('\n');
  
  const result = {
    file: filePath,
    lines: lines.length,
    type: ext,
    issues: [],
    metrics: {}
  };
  
  // 基本分析
  result.metrics = {
    codeLines: lines.filter(l => l.trim() && !l.trim().startsWith('//') && !l.trim().startsWith('#')).length,
    commentLines: lines.filter(l => l.trim().startsWith('//') || l.trim().startsWith('#') || l.trim().startsWith('/*')).length,
    blankLines: lines.filter(l => !l.trim()).length
  };
  
  // AI 生成特征检测
  if (options.checkAi || options.quality) {
    result.aiIndicators = detectAICode(content, lines);
  }
  
  // 质量检查
  if (options.quality) {
    result.quality = analyzeQuality(content, lines, ext);
  }
  
  // 安全检查
  if (options.security) {
    result.security = analyzeSecurity(content, ext);
  }
  
  // 函数分析（JS/TS）
  if (['.js', '.ts', '.jsx', '.tsx'].includes(ext)) {
    result.functions = extractFunctions(content);
  }
  
  return result;
}

function detectAICode(content, lines) {
  const indicators = [];
  
  // AI 生成特征
  const aiPatterns = [
    { pattern: /\/\/ .* generated by/i, desc: 'AI 生成注释' },
    { pattern: /\/\/ auto-generated/i, desc: '自动生成标记' },
    { pattern: /TODO:.*implement/i, desc: '未实现的 TODO' },
    { pattern: /FIXME:/i, desc: 'FIXME 标记' },
    { pattern: /\/\*[\s\S]*?\*\//g, desc: '大段注释' }
  ];
  
  aiPatterns.forEach(({ pattern, desc }) => {
    if (pattern.test(content)) {
      indicators.push(desc);
    }
  });
  
  // 重复代码检测
  const codeLines = lines.filter(l => l.trim() && !l.trim().startsWith('//'));
  const uniqueLines = new Set(codeLines.map(l => l.trim()));
  const duplicateRatio = 1 - (uniqueLines.size / codeLines.length);
  
  if (duplicateRatio > 0.1) {
    indicators.push(`重复代码比例: ${(duplicateRatio * 100).toFixed(1)}%`);
  }
  
  return {
    detected: indicators.length > 0,
    indicators,
    duplicateRatio
  };
}

function analyzeQuality(content, lines, ext) {
  const issues = [];
  const metrics = {};
  
  // 行长度检查
  const longLines = lines.filter(l => l.length > 120);
  if (longLines.length > 0) {
    issues.push({
      type: 'style',
      message: `${longLines.length} 行超过 120 字符`,
      severity: 'warning'
    });
  }
  
  // 函数长度检查（JS/TS）
  if (['.js', '.ts', '.jsx', '.tsx'].includes(ext)) {
    const functions = content.match(/function\s+\w+\s*\([^)]*\)\s*\{[\s\S]*?\n\}/g) || [];
    const longFunctions = functions.filter(f => f.split('\n').length > 50);
    
    if (longFunctions.length > 0) {
      issues.push({
        type: 'complexity',
        message: `${longFunctions.length} 个函数超过 50 行`,
        severity: 'warning'
      });
    }
    
    metrics.functionCount = functions.length;
    metrics.avgFunctionLength = functions.length > 0 
      ? functions.reduce((sum, f) => sum + f.split('\n').length, 0) / functions.length
      : 0;
  }
  
  // TODO/FIXME 统计
  const todos = (content.match(/TODO:/gi) || []).length;
  const fixmes = (content.match(/FIXME:/gi) || []).length;
  
  if (todos > 0 || fixmes > 0) {
    issues.push({
      type: 'todos',
      message: `${todos} TODOs, ${fixmes} FIXMEs`,
      severity: 'info'
    });
  }
  
  return {
    score: Math.max(0, 100 - issues.filter(i => i.severity === 'warning').length * 10),
    issues,
    metrics
  };
}

function analyzeSecurity(content, ext) {
  const vulnerabilities = [];
  
  // 常见安全问题
  const securityPatterns = [
    { pattern: /eval\s*\(/g, desc: 'eval() 使用 - 潜在代码注入风险', severity: 'high' },
    { pattern: /innerHTML\s*=/g, desc: 'innerHTML 赋值 - XSS 风险', severity: 'medium' },
    { pattern: /document\.write/g, desc: 'document.write - XSS 风险', severity: 'medium' },
    { pattern: /password\s*=\s*['"]/, desc: '硬编码密码', severity: 'high' },
    { pattern: /api[_-]?key\s*=\s*['"]/, desc: '硬编码 API key', severity: 'high' },
    { pattern: /secret\s*=\s*['"]/, desc: '硬编码密钥', severity: 'high' }
  ];
  
  securityPatterns.forEach(({ pattern, desc, severity }) => {
    const matches = content.match(pattern);
    if (matches) {
      vulnerabilities.push({
        type: desc,
        severity,
        count: matches.length
      });
    }
  });
  
  return {
    secure: vulnerabilities.filter(v => v.severity === 'high').length === 0,
    vulnerabilities
  };
}

function extractFunctions(content) {
  const functions = [];
  
  // 简单的函数提取（JS/TS）
  const funcPattern = /(?:function\s+(\w+)|(?:const|let|var)\s+(\w+)\s*=\s*(?:async\s*)?\([^)]*\)\s*=>)/g;
  let match;
  
  while ((match = funcPattern.exec(content)) !== null) {
    functions.push({
      name: match[1] || match[2],
      line: content.substring(0, match.index).split('\n').length
    });
  }
  
  return functions;
}

async function getFiles(dirPath, type) {
  const extensions = {
    js: ['.js', '.jsx'],
    ts: ['.ts', '.tsx'],
    py: ['.py'],
    all: ['.js', '.jsx', '.ts', '.tsx', '.py', '.json', '.md']
  };
  
  const allowedExts = extensions[type] || extensions.all;
  const files = [];
  
  async function walk(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      
      if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
        await walk(fullPath);
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name);
        if (allowedExts.includes(ext)) {
          files.push(fullPath);
        }
      }
    }
  }
  
  await walk(dirPath);
  return files;
}

async function outputResults(results, options) {
  const format = options.format || 'text';
  
  if (format === 'json') {
    const output = JSON.stringify(results, null, 2);
    if (options.output) {
      await fs.writeFile(options.output, output, 'utf-8');
      console.log(chalk.green(`\n✓ 结果已保存到: ${options.output}\n`));
    } else {
      console.log(output);
    }
  } else {
    // 文本格式输出
    console.log(chalk.bold('\n分析结果:\n'));
    
    if (results.summary) {
      console.log(chalk.cyan('摘要:'));
      console.log(`  文件数: ${results.summary.totalFiles}`);
      console.log(`  总行数: ${results.summary.totalLines}`);
      console.log(`  函数数: ${results.summary.totalFunctions}`);
      
      if (results.summary.issues.length > 0) {
        console.log(chalk.yellow(`  问题: ${results.summary.issues.length}`));
      }
    }
    
    if (results.files) {
      console.log(chalk.cyan('\n文件详情:'));
      results.files.slice(0, 5).forEach(f => {
        console.log(`\n  ${f.file}`);
        console.log(chalk.gray(`    行数: ${f.lines}`));
        if (f.quality) {
          console.log(chalk.gray(`    质量评分: ${f.quality.score}/100`));
        }
        if (f.aiIndicators?.detected) {
          console.log(chalk.yellow(`    AI 生成特征: ${f.aiIndicators.indicators.join(', ')}`));
        }
      });
    }
    
    console.log();
  }
}
