function generateContext(target, analysis) {
  switch (target) {
    case 'agents.md': return generateAgentsMd(analysis);
    case 'cursorrules': return generateCursorRules(analysis);
    case 'claude.md': return generateClaudeMd(analysis);
    case 'context.md': return generateContextMd(analysis);
    default: return generateContextMd(analysis);
  }
}

function generateAgentsMd(a) {
  const techLines = [];
  a.languages.forEach(l => techLines.push(`**Language:** ${l}`));
  a.frameworks.forEach(f => techLines.push(`**Framework:** ${f}`));
  a.tools.forEach(t => techLines.push(`**Tool:** ${t}`));

  const lines = [
    `# AGENTS.md - ${a.repoName}`,
    '',
    '## Project Overview',
    a.readme ? _extractSummary(a.readme) : `This is the ${a.repoName} project.`,
    '',
    '## Tech Stack',
    ...techLines,
  ];

  if (a.keyDirs.length) {
    lines.push('', '## Project Structure');
    a.keyDirs.forEach(d => lines.push(`- \`${d}/\``));
  }

  if (a.conventions.length) {
    lines.push('', '## Conventions');
    a.conventions.forEach(c => lines.push(`- ${c}`));
  }

  lines.push(
    '',
    '## Development',
    '',
    '### Setup',
    '```bash',
    _hasTool(a, 'Node.js') ? 'npm install' : '# Install dependencies as needed',
    '```',
    '',
    '### Build',
    '```bash',
    _hasTool(a, 'Node.js') ? 'npm run build' : '# Build as needed',
    '```',
    '',
    '### Test',
    '```bash',
    _hasTool(a, 'Node.js') ? 'npm test' : '# Run tests as needed',
    '```',
    '',
    '## Important Notes',
    '- Keep changes consistent with existing code style',
    '- Follow the established patterns in the codebase',
    '- Run tests before submitting changes',
    '',
    `_Generated by ctxgen on ${new Date().toISOString().split('T')[0]}_`
  );

  return lines.join('\n');
}

function generateCursorRules(a) {
  const lines = [
    `# ${a.repoName} - Cursor Rules`,
    ''
  ];

  if (a.languages.length) {
    lines.push(`Primary language: ${a.languages[0]}`);
  }
  if (a.frameworks.length) {
    lines.push(`Frameworks: ${a.frameworks.join(', ')}`);
  }

  lines.push(
    '',
    '## Code Style'
  );
  a.conventions.forEach(c => lines.push(`- ${c}`));

  lines.push(
    '',
    '## Guidelines',
    '- Follow existing code patterns and conventions',
    '- Keep functions small and focused',
    '- Write descriptive commit messages',
    '- Add tests for new functionality'
  );

  if (_hasTool(a, 'TypeScript')) {
    lines.push('- Use strict TypeScript types, avoid `any`');
    lines.push('- Prefer interfaces over type aliases for objects');
  }

  if (_hasTool(a, 'React') || a.frameworks.includes('React') || a.frameworks.includes('Next.js')) {
    lines.push('- Use functional components with hooks');
    lines.push('- Keep component state minimal');
    lines.push('- Follow React best practices for performance');
  }

  lines.push('', `_Generated by ctxgen on ${new Date().toISOString().split('T')[0]}_`);
  return lines.join('\n');
}

function generateClaudeMd(a) {
  const lines = [
    `# CLAUDE.md`,
    '',
    `## Project: ${a.repoName}`,
    '',
    '### Tech Stack'
  ];

  const stackItems = [...a.languages, ...a.frameworks, ...a.tools];
  stackItems.forEach(item => lines.push(`- ${item}`));

  lines.push('', '### Structure');
  a.keyDirs.forEach(d => lines.push(`- \`${d}/\``));

  if (a.conventions.length) {
    lines.push('', '### Conventions');
    a.conventions.forEach(c => lines.push(`- ${c}`));
  }

  lines.push(
    '',
    '### Instructions',
    '- Read existing code before making changes',
    '- Follow the established patterns',
    '- Keep changes minimal and focused',
    '- Ensure all tests pass',
    '',
    `_Generated by ctxgen on ${new Date().toISOString().split('T')[0]}_`
  );

  return lines.join('\n');
}

function generateContextMd(a) {
  const lines = [
    `# ${a.repoName} - AI Context`,
    '',
    '## Summary',
    a.readme ? _extractSummary(a.readme) : `${a.repoName} project.`,
    '',
    '## Technology',
    `Languages: ${a.languages.join(', ') || 'N/A'}`,
    `Frameworks: ${a.frameworks.join(', ') || 'None detected'}`,
    `Tools: ${a.tools.join(', ') || 'None detected'}`,
    '',
    '## Directory Layout'
  ];

  a.keyDirs.forEach(d => lines.push(`- \`${d}/\``));

  lines.push('', '## Conventions');
  if (a.conventions.length > 0) {
    a.conventions.forEach(c => lines.push(`- ${c}`));
  } else {
    lines.push('No specific conventions detected.');
  }

  lines.push(
    '',
    `Files analyzed: ${a.fileCount}`,
    '',
    `_Generated by ctxgen on ${new Date().toISOString().split('T')[0]}_`
  );

  return lines.join('\n');
}

function _extractSummary(readme) {
  const readmeLines = readme.split('\n').filter(l => l.trim() && !l.startsWith('#'));
  return readmeLines.slice(0, 5).join('\n').slice(0, 500) || 'No summary available.';
}

function _hasTool(a, name) {
  return a.tools.includes(name) || a.languages.includes(name);
}

module.exports = { generateContext };
